language: node_js
node_js:
- '6.0'
cache:
  directories: 
  - node_modules/
branches:
  only:
  - master
notifications:
  email: false
before_script:
  - npm install
script:
  - ./node_modules/.bin/firebase-server -p 5000 -d '{"sampleCounts": {a:0, b:0, c:0, d:0, e:0}}' &
  - npm run unit

